postgreconfig:
  dbname: "XData"
  link: "172.31.20.39"
  port: 5432
  user: "postgres"
  passwd: "swz123456"


mogodbconfig:
  dbname: "XDATA"
  link: "172.31.20.39"
  port: 27017
  passwd: ""

redisconfig:
  dbname: 0
  link: "192.168.2.2"
  port: 6379
  passwd: ""